version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
    - dependency-name: k8s.io/*
    - dependency-name: github.com/grpc-ecosystem/*
    - dependency-name: google.golang.org/grpc
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    # ignore all non-security updates: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit
    open-pull-requests-limit: 0
    labels:
      - type/dependencies
      - github_actions
    commit-message:
      prefix: chore(deps-dev)
